#!/usr/bin/env python3
"""Build a normalized command-presence comparison of nvi vs govi usage dumps.

Both editors describe one-or-more command glyphs followed by an English
description per line, but they format differently: nvi lists one glyph per line
and right-aligns "name:"; govi groups several glyphs on a line ("a A i I o O
insert text"). To compare WHICH commands each lists, we extract the leading
glyph tokens of every line (the run before the description starts) and set-diff.

Heuristic for "where the description starts": the first field whose first two
characters are both ascii lowercase letters (e.g. "insert", "delete", "change/..").
Single/upper/control/<...>/punct glyphs before that are treated as commands.
Imperfect (a hypothetical lowercase 2+ char command like "gg" would be missed),
so treat the result as a guide and confirm against the raw .diff files.
"""
import sys, re

def is_desc_start(tok):
    return len(tok) >= 2 and tok[0].islower() and tok[1].islower() and tok[0].isascii() and tok[1].isascii()

def glyphs(path, exmode):
    out = set()
    for line in open(path):
        line = line.rstrip("\n")
        if not line.strip():
            continue
        if exmode:
            # "name: desc" (possibly right-aligned). Token = text before first ':'.
            if ":" in line:
                out.add(line.split(":", 1)[0].strip())
            continue
        fields = line.split()
        for f in fields:
            if is_desc_start(f):
                break
            out.add(f)
    return out

def section(title, a_name, a, b_name, b):
    lines = [f"===== {title} ====="]
    lines.append(f"--- listed by {a_name} but NOT {b_name} ---")
    lines += sorted(a - b) or ["(none)"]
    lines.append(f"--- listed by {b_name} but NOT {a_name} ---")
    lines += sorted(b - a) or ["(none)"]
    lines.append(f"--- listed by BOTH ({len(a & b)}) ---")
    lines.append(" ".join(sorted(a & b)))
    lines.append("")
    return "\n".join(lines)

hdr = [
    "Normalized command-presence comparison (nvi vs govi), generated by mkcompare.py.",
    "CAVEAT: glyph extraction is heuristic (see the script docstring); govi groups",
    "several command glyphs per line while nvi uses one-per-line, and notation differs",
    "(nvi '^[' vs govi '<esc>'; nvi '[Ee]dit' vs govi 'edit'). Use this as a guide and",
    "confirm specifics against the *.raw.diff.txt and the source .txt captures.",
    "",
]
out = "\n".join(hdr)
out += section("viusage (vi-mode commands)",
               "nvi", glyphs("nvi.viusage.txt", False),
               "govi", glyphs("govi.viusage.txt", False))
out += section("exusage (ex-mode commands)",
               "nvi", glyphs("nvi.exusage.txt", True),
               "govi", glyphs("govi.exusage.txt", True))
open("usage.commands.compare.txt", "w").write(out)
sys.stdout.write(out)
